language: node_js
node_js:
  - '10.15.0'

script:
  - echo "deploying..."

install:
  - npm i
  - npm run build
  - npm i firebase-tools -g

after_success:
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
